# Generated by Django 6.0.3 on 2026-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturantapp', '0007_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=10),
        ),
    ]
